name: '📦 Publish to Nuget'
on:
  workflow_dispatch:

jobs:
  publish:
    name: '📦 Publish to Nuget'
    runs-on: ubuntu-latest
    steps:
      - name: '🧾 Checkout'
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_BASIC }}

      - uses: actions/setup-dotnet@v3
        name: 💽 Setup .NET SDK
        with:
          global-json-file: src/global.json
      
      - name: 📦 Publish
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Chickensoft.GodotPackageTemplate.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
